In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model



In [27]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [28]:
a=3

In [29]:
df.bedrooms = df.bedrooms.fillna(a)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [30]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']], df.price)

LinearRegression()

In [31]:
reg.coef_

array([  119.67905405, 13097.24903475, -4207.28764479])

In [32]:
reg.intercept_

256461.14864864858

In [33]:
reg.predict([[3000,3,15]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([591680.74324324])

In [37]:
reg.predict([[5500,4,4]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([950255.79150579])